# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MQTT_UI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 605)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 605))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 605))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("leaf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 280, 1021, 281))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 321, 257))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout.addWidget(self.pushButton_14, 8, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 5, 1, 1, 1)
        self.pushButton_1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.gridLayout.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout.addWidget(self.pushButton_11, 7, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 4, 1, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout.addWidget(self.pushButton_13, 8, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout.addWidget(self.pushButton_9, 6, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout.addWidget(self.pushButton_15, 9, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 5, 0, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout.addWidget(self.pushButton_12, 7, 1, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout.addWidget(self.pushButton_10, 6, 1, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout.addWidget(self.pushButton_16, 9, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 321, 101))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_1 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_1)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_4 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 129, 321, 131))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_17 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_2.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_2.addWidget(self.pushButton_18, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 19, 321, 241))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.progressBar_1 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_1.setProperty("value", 10)
        self.progressBar_1.setObjectName(_fromUtf8("progressBar_1"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.progressBar_1)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.progressBar_2 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_2.setProperty("value", 20)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.progressBar_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.progressBar_3 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_3.setProperty("value", 30)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.progressBar_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.progressBar_4 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_4.setProperty("value", 40)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.progressBar_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.progressBar_5 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_5.setProperty("value", 50)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.progressBar_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.progressBar_6 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_6.setProperty("value", 60)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.progressBar_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.progressBar_7 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_7.setProperty("value", 70)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.progressBar_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.progressBar_8 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_8.setProperty("value", 80)
        self.progressBar_8.setObjectName(_fromUtf8("progressBar_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.progressBar_8)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.progressBar_9 = QtGui.QProgressBar(self.formLayoutWidget)
        self.progressBar_9.setProperty("value", 90)
        self.progressBar_9.setTextVisible(True)
        self.progressBar_9.setInvertedAppearance(False)
        self.progressBar_9.setObjectName(_fromUtf8("progressBar_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.progressBar_9)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 9, 1011, 261))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 991, 161))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_5 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_9 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 189, 991, 61))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_21 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_4.addWidget(self.pushButton_21, 1, 2, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_4.addWidget(self.pushButton_19, 1, 0, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_4.addWidget(self.pushButton_24, 2, 2, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_4.addWidget(self.pushButton_22, 2, 0, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_4.addWidget(self.pushButton_20, 1, 1, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_4.addWidget(self.pushButton_23, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.pushButton_20)
        MainWindow.setTabOrder(self.pushButton_20, self.pushButton_21)
        MainWindow.setTabOrder(self.pushButton_21, self.pushButton_22)
        MainWindow.setTabOrder(self.pushButton_22, self.pushButton_23)
        MainWindow.setTabOrder(self.pushButton_23, self.pushButton_24)
        MainWindow.setTabOrder(self.pushButton_24, self.pushButton_1)
        MainWindow.setTabOrder(self.pushButton_1, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_12)
        MainWindow.setTabOrder(self.pushButton_12, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.pushButton_16)
        MainWindow.setTabOrder(self.pushButton_16, self.lineEdit_1)
        MainWindow.setTabOrder(self.lineEdit_1, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.pushButton_17)
        MainWindow.setTabOrder(self.pushButton_17, self.pushButton_18)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Food Computer MQTT Test", None))
        self.groupBox.setTitle(_translate("MainWindow", "Relays (Publish)", None))
        self.pushButton_5.setText(_translate("MainWindow", "Relay 3 ON", None))
        self.pushButton_14.setText(_translate("MainWindow", "Relay 7 OFF", None))
        self.pushButton_2.setText(_translate("MainWindow", "Relay 1 OFF", None))
        self.pushButton_8.setText(_translate("MainWindow", "Relay 4 OFF", None))
        self.pushButton_1.setText(_translate("MainWindow", "Relay 1 ON", None))
        self.pushButton_11.setText(_translate("MainWindow", "Relay 6 ON", None))
        self.pushButton_6.setText(_translate("MainWindow", "Relay 3 OFF", None))
        self.pushButton_13.setText(_translate("MainWindow", "Relay 7 ON", None))
        self.pushButton_3.setText(_translate("MainWindow", "Relay 2 ON", None))
        self.pushButton_9.setText(_translate("MainWindow", "Relay 5 ON", None))
        self.pushButton_4.setText(_translate("MainWindow", "Relay 2 OFF", None))
        self.pushButton_15.setText(_translate("MainWindow", "Relay 8 ON", None))
        self.pushButton_7.setText(_translate("MainWindow", "Relay 4 ON", None))
        self.pushButton_12.setText(_translate("MainWindow", "Relay 6 OFF", None))
        self.pushButton_10.setText(_translate("MainWindow", "Relay 5 OFF", None))
        self.pushButton_16.setText(_translate("MainWindow", "Relay 8 OFF", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "MQTT for Buttons and Sensors", None))
        self.label_10.setText(_translate("MainWindow", "MQTT Broker\'s IP", None))
        self.lineEdit_1.setText(_translate("MainWindow", "192.168.1.4", None))
        self.label_11.setText(_translate("MainWindow", "MQTT Broker\'s Port", None))
        self.lineEdit_2.setText(_translate("MainWindow", "1884", None))
        self.lineEdit_3.setText(_translate("MainWindow", "/food_computer_1/controls", None))
        self.label_13.setText(_translate("MainWindow", "Subcribe Topic (Sensors)", None))
        self.lineEdit_4.setText(_translate("MainWindow", "/food_computer_1/sensors", None))
        self.label_12.setText(_translate("MainWindow", "Publish Topic (Buttons)", None))
        self.pushButton_17.setText(_translate("MainWindow", "Connect and Subscribe", None))
        self.pushButton_18.setText(_translate("MainWindow", "Reconnect", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sensors (Subscribed)", None))
        self.label.setText(_translate("MainWindow", "Air CO2", None))
        self.label_2.setText(_translate("MainWindow", "Air Humidity", None))
        self.label_3.setText(_translate("MainWindow", "Air Temp", None))
        self.label_4.setText(_translate("MainWindow", "Water Temp", None))
        self.label_5.setText(_translate("MainWindow", "Water EC", None))
        self.label_6.setText(_translate("MainWindow", "Water pH", None))
        self.label_7.setText(_translate("MainWindow", "Light Lux", None))
        self.label_8.setText(_translate("MainWindow", "Window Switch", None))
        self.label_9.setText(_translate("MainWindow", "Shell Switch", None))
        self.progressBar_9.setFormat(_translate("MainWindow", "%p%", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "MQTT Broker Test", None))
        self.label_14.setText(_translate("MainWindow", "MQTT Broker\'s IP", None))
        self.label_15.setText(_translate("MainWindow", "MQTT Broker\'s Port", None))
        self.label_16.setText(_translate("MainWindow", "Subscribing Topic", None))
        self.label_17.setText(_translate("MainWindow", "Publishing Topic", None))
        self.label_18.setText(_translate("MainWindow", "Received Payload", None))
        self.label_19.setText(_translate("MainWindow", "Payload to Publish", None))
        self.lineEdit_5.setText(_translate("MainWindow", "192.168.1.4", None))
        self.lineEdit_6.setText(_translate("MainWindow", "1884", None))
        self.lineEdit_7.setText(_translate("MainWindow", "/topic", None))
        self.lineEdit_8.setText(_translate("MainWindow", "/topic", None))
        self.lineEdit_10.setText(_translate("MainWindow", "Hello World", None))
        self.pushButton_21.setText(_translate("MainWindow", "Reconnect", None))
        self.pushButton_19.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_24.setText(_translate("MainWindow", "Unsubscribe", None))
        self.pushButton_22.setText(_translate("MainWindow", "Publish", None))
        self.pushButton_20.setText(_translate("MainWindow", "Disconnect", None))
        self.pushButton_23.setText(_translate("MainWindow", "Subscribe", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

